# Generated by Django 4.1.7 on 2023-04-16 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_id",
        ),
    ]
