# Generated by Django 4.1.7 on 2023-04-26 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="User",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.user",
            ),
        ),
    ]
